### ISSUE TITLE
Syntax highlighting is broken after update

### ISSUE THREAD

**Issue by eshepelyuk** [IndianBoy42/tree-sitter-just#49]
Hello

I've just updated the plugin to the latest version and now my justfiles are not having syntax highlighting at all.

**Comment by tgross35** [comment]
@eshepelyuk hello, are you able to provide some more debugging information? Specific commit and general setup would be good.

Some things changed with the paths, that may need to be adjusted.

**Comment by eshepelyuk** [comment]
> @eshepelyuk hello, are you able to provide some more debugging information? Specific commit and general setup would be good.
> 
> Some things changed with the paths, that may need to be adjusted.

* Commit is https://github.com/IndianBoy42/tree-sitter-just/commit/023fee132e1ca8d72c47352bfdbcbb598ab173a5
* `general setup` I am not sure what does it mean

**Comment by eshepelyuk** [comment]
This is my "reduced" config

```
call plug#begin(stdpath('data') . '/plugged')

Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'IndianBoy42/tree-sitter-just'

call plug#end()

lua <<EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = {"bash", "dockerfile", "yaml", "json", "json5", "vim", "python", "regex",
        "lua", "c_sharp", "html", "typescript", "javascript", "comment", "toml", "just"},
    highlight = {enable = true},
    indent = {enable = true},
}

require"tree-sitter-just".setup {}

EOF
```

**Comment by eshepelyuk** [comment]
This is `justfile` example

```
# list available receipes
@default:
  just --list

_py:
  #!/usr/bin/env bash
  set -euo pipefail

  if [ ! -d .venv ]; then
      python3 -mvenv .venv
      source .venv/bin/activate
      pip3 install -r requirements.txt
  fi

up: _py
  #!/usr/bin/env bash
  set -euo pipefail

  source .venv/bin/activate
  mkdocs serve --dirtyreload

lint: lint-cspell

lint-cspell:
  npx cspell lint 'docs/**/*.md'
```

**Comment by eshepelyuk** [comment]
This is output of `InspectTree`
```
(item) ; [1:1 - 2:0]
 (eol) ; [1:1 - 2:0]
  (comment) ; [1:1 - 2:0]
(item) ; [2:1 - 5:0]
 (recipe) ; [2:1 - 5:0]
  (recipe_header) ; [2:1 - 9]
   recipe_name: (identifier) ; [2:2 - 8]
  (recipe_body) ; [3:3 - 5:0]
   contents: (recipe_line) ; [3:3 - 5:0]
    (text) ; [3:3 - 13]
(item) ; [5:1 - 15:0]
 (recipe) ; [5:1 - 15:0]
  (recipe_header) ; [5:1 - 4]
   recipe_name: (identifier) ; [5:1 - 3]
  (recipe_body) ; [6:3 - 15:0]
   contents: (shebang) ; [6:3 - 7:0]
   contents: (recipe_line) ; [7:1 - 9:0]
    (text) ; [7:1 - 19]
   contents: (recipe_line) ; [9:1 - 10:0]
    (text) ; [9:1 - 25]
   contents: (recipe_line) ; [10:1 - 11:0]
    (text) ; [10:1 - 26]
   contents: (recipe_line) ; [11:1 - 12:0]
    (text) ; [11:1 - 31]
   contents: (recipe_line) ; [12:1 - 13:0]
    (text) ; [12:1 - 38]
   contents: (recipe_line) ; [13:1 - 15:0]
    (text) ; [13:1 - 4]
(item) ; [15:1 - 22:0]
 (recipe) ; [15:1 - 22:0]
  (recipe_header) ; [15:1 - 7]
   recipe_name: (identifier) ; [15:1 - 2]
   (dependencies) ; [15:4 - 7]
    (dependency) ; [15:4 - 7]
     recipe: (identifier) ; [15:4 - 7]
  (recipe_body) ; [16:3 - 22:0]
   contents: (shebang) ; [16:3 - 17:0]
   contents: (recipe_line) ; [17:1 - 19:0]
    (text) ; [17:1 - 19]
   contents: (recipe_line) ; [19:1 - 20:0]
    (text) ; [19:1 - 27]
   contents: (recipe_line) ; [20:1 - 22:0]
    (text) ; [20:1 - 28]
(item) ; [22:1 - 24:0]
 (recipe) ; [22:1 - 24:0]
  (recipe_header) ; [22:1 - 17]
   recipe_name: (identifier) ; [22:1 - 4]
   (dependencies) ; [22:6 - 17]
    (dependency) ; [22:6 - 17]
     recipe: (identifier) ; [22:6 - 17]
(item) ; [24:1 - 26:0]
 (recipe) ; [24:1 - 26:0]
  (recipe_header) ; [24:1 - 12]
   recipe_name: (identifier) ; [24:1 - 11]
  (recipe_body) ; [25:3 - 26:0]
   contents: (recipe_line) ; [25:3 - 26:0]
    (text) ; [25:3 - 32]
(item) ; [26:1 - 0]
 (eol) ; [26:1 - 0]
```

**Comment by tgross35** [comment]
Thanks for all the info. It looks like the parser is working fine but it can't find the queries.

I moved them from `queries/just/` to just `queries/` to be in line with the other tree sitter languages, I just need to figure out how to update nvim to follow them

**Comment by eshepelyuk** [comment]
> Thanks for all the info. It looks like the parser is working fine but it can't find the queries.
> 
> I moved them from `queries/just/` to just `queries/` to be in line with the other tree sitter languages, I just need to figure out how to update nvim to follow them

Great :)

**Comment by tgross35** [comment]
@eshepelyuk this should be fixed with the latest commit, would you mind checking?

**Comment by eshepelyuk** [comment]
@tgross35 it's still not working

After update I am receiving this error 

```
nvim-treesitter[just]: Error during compilation
cc1plus: fatal error: src/scanner.cc: No such file or directory
compilation terminated.
```

**Comment by tgross35** [comment]
Ah, can you change `files = { "src/parser.c", "src/scanner.cc" }` to `files = { "src/parser.c", "src/scanner.c" }`

**Comment by eshepelyuk** [comment]
> Ah, can you change `files = { "src/parser.c", "src/scanner.cc" }` to `files = { "src/parser.c", "src/scanner.c" }`

@tgross35 I don't understand what do you mean with this. I don't have such snippets anywhere.

**Comment by eshepelyuk** [comment]
Looks like fixed in latest versions, thanks.

**Comment by eshepelyuk** [comment]
@tgross35 

the plugin is broken again after the latest update :(

when calling `TSInstall just` the following error is shown 

```
Failed to execute the following command:
{
  cmd = <function 1>
}
"...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:452: assertion
```

I also tried in previous NeoVim version 0.9.4 - and it show the same error.


PS: It's great that plugin had revived and new features are added, but probably it requires event more attention to testing before releasing new version, to avoid such failures.

**Comment by tgross35** [comment]
Thanks, I will take a look.

Do you have any idea how to run better nvim tests in CI? Tree-sitter CLI has highlighting tests that I have used pretty extensively (https://github.com/IndianBoy42/tree-sitter-just/blob/d016423ddf36689873f49889265306f90372912d/test/highlight/statements.just), but all I can do is spot check NeoVim and that's proving impossible. Seems like every setup is slightly different, I'm not sure what is unique about mine...

PR highly welcome if you have any ideas, maybe the parser can be instrumented somehow.

**Comment by eshepelyuk** [comment]
The latest commit is the reason of failure d016423ddf36689873f49889265306f90372912d

The previous one 7765fb33c6f42239ee2a88d86d460fbfb9f86ca7 works fine.

**Comment by tgross35** [comment]
I just reverted that change for now https://github.com/IndianBoy42/tree-sitter-just/pull/65

Started a brief skeleton of a nvim CI setup here https://github.com/IndianBoy42/tree-sitter-just/pull/64. Do you know of any easy way to have nvim tell us whether or not it can read the queries and parse a file over CLI?

**Comment by eshepelyuk** [comment]
> I just reverted that change for now https://github.com/IndianBoy42/tree-sitter-just/pull/65
> 
> Started a brief skeleton of a nvim CI setup here https://github.com/IndianBoy42/tree-sitter-just/pull/64. Do you know of any easy way to have nvim tell us whether or not it can read the queries and parse a file over CLI?

Hi

unfortunately i am quite noob in nvim internals \ api \ etc. 
apart of plugin config i haven't touched it.
